title: Rebel Queen Starla’s bookquest
email: captain.medusa@proton.me
description: >- # this means to ignore newlines until "baseurl:"
  Blog littéraire de SFFF&F : science-fiction, fantasy, fantastique & feminisme !
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  puzzles:
    output: true
  books:
    output: true

defaults:
  - scope:
      path: ""
      type: "puzzles"
    values:
      layout: "puzzle"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"