url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Rebel Queen Starla's Bookquest" # the name of your site, e.g. ACME Corp.

collections:
  puzzles:
    output: true
  books:
    output: true

defaults:
  - scope:
      path: ""
      type: "puzzles"
    values:
      layout: "puzzle"
  - scope:
      path: ""
      type: "books"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"